// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/reminderpb.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reminder struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Tags                 []string             `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	TeamMember           string               `protobuf:"bytes,5,opt,name=team_member,json=teamMember,proto3" json:"team_member,omitempty"`
	Priority             int64                `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Reminder) Reset()         { *m = Reminder{} }
func (m *Reminder) String() string { return proto.CompactTextString(m) }
func (*Reminder) ProtoMessage()    {}
func (*Reminder) Descriptor() ([]byte, []int) {
	return fileDescriptor_4736cf873f19cb14, []int{0}
}

func (m *Reminder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reminder.Unmarshal(m, b)
}
func (m *Reminder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reminder.Marshal(b, m, deterministic)
}
func (m *Reminder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reminder.Merge(m, src)
}
func (m *Reminder) XXX_Size() int {
	return xxx_messageInfo_Reminder.Size(m)
}
func (m *Reminder) XXX_DiscardUnknown() {
	xxx_messageInfo_Reminder.DiscardUnknown(m)
}

var xxx_messageInfo_Reminder proto.InternalMessageInfo

func (m *Reminder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reminder) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reminder) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *Reminder) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Reminder) GetTeamMember() string {
	if m != nil {
		return m.TeamMember
	}
	return ""
}

func (m *Reminder) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type ReminderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReminderRequest) Reset()         { *m = ReminderRequest{} }
func (m *ReminderRequest) String() string { return proto.CompactTextString(m) }
func (*ReminderRequest) ProtoMessage()    {}
func (*ReminderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4736cf873f19cb14, []int{1}
}

func (m *ReminderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReminderRequest.Unmarshal(m, b)
}
func (m *ReminderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReminderRequest.Marshal(b, m, deterministic)
}
func (m *ReminderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReminderRequest.Merge(m, src)
}
func (m *ReminderRequest) XXX_Size() int {
	return xxx_messageInfo_ReminderRequest.Size(m)
}
func (m *ReminderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReminderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReminderRequest proto.InternalMessageInfo

func (m *ReminderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReminderResponse struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReminderResponse) Reset()         { *m = ReminderResponse{} }
func (m *ReminderResponse) String() string { return proto.CompactTextString(m) }
func (*ReminderResponse) ProtoMessage()    {}
func (*ReminderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4736cf873f19cb14, []int{2}
}

func (m *ReminderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReminderResponse.Unmarshal(m, b)
}
func (m *ReminderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReminderResponse.Marshal(b, m, deterministic)
}
func (m *ReminderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReminderResponse.Merge(m, src)
}
func (m *ReminderResponse) XXX_Size() int {
	return xxx_messageInfo_ReminderResponse.Size(m)
}
func (m *ReminderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReminderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReminderResponse proto.InternalMessageInfo

func (m *ReminderResponse) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type SetReminderRequest struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetReminderRequest) Reset()         { *m = SetReminderRequest{} }
func (m *SetReminderRequest) String() string { return proto.CompactTextString(m) }
func (*SetReminderRequest) ProtoMessage()    {}
func (*SetReminderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4736cf873f19cb14, []int{3}
}

func (m *SetReminderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReminderRequest.Unmarshal(m, b)
}
func (m *SetReminderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReminderRequest.Marshal(b, m, deterministic)
}
func (m *SetReminderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReminderRequest.Merge(m, src)
}
func (m *SetReminderRequest) XXX_Size() int {
	return xxx_messageInfo_SetReminderRequest.Size(m)
}
func (m *SetReminderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReminderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetReminderRequest proto.InternalMessageInfo

func (m *SetReminderRequest) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type SetReminderResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReminderResponse) Reset()         { *m = SetReminderResponse{} }
func (m *SetReminderResponse) String() string { return proto.CompactTextString(m) }
func (*SetReminderResponse) ProtoMessage()    {}
func (*SetReminderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4736cf873f19cb14, []int{4}
}

func (m *SetReminderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReminderResponse.Unmarshal(m, b)
}
func (m *SetReminderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReminderResponse.Marshal(b, m, deterministic)
}
func (m *SetReminderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReminderResponse.Merge(m, src)
}
func (m *SetReminderResponse) XXX_Size() int {
	return xxx_messageInfo_SetReminderResponse.Size(m)
}
func (m *SetReminderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReminderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetReminderResponse proto.InternalMessageInfo

func (m *SetReminderResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Reminder)(nil), "reminder.Reminder")
	proto.RegisterType((*ReminderRequest)(nil), "reminder.ReminderRequest")
	proto.RegisterType((*ReminderResponse)(nil), "reminder.ReminderResponse")
	proto.RegisterType((*SetReminderRequest)(nil), "reminder.SetReminderRequest")
	proto.RegisterType((*SetReminderResponse)(nil), "reminder.SetReminderResponse")
}

func init() { proto.RegisterFile("proto/reminderpb.proto", fileDescriptor_4736cf873f19cb14) }

var fileDescriptor_4736cf873f19cb14 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0x5f, 0xd3, 0x29, 0xff, 0xbf, 0x32, 0x82, 0xac, 0x41, 0x69, 0x0c, 0x08, 0x39,
	0x6d, 0xa1, 0x82, 0x1f, 0xa0, 0x14, 0x5f, 0x0e, 0x5e, 0x52, 0x4f, 0x5e, 0x24, 0x35, 0x63, 0x58,
	0xe8, 0x36, 0x71, 0x77, 0x2b, 0xf4, 0xf3, 0xf8, 0x39, 0xfc, 0x6e, 0xe2, 0xa6, 0x9b, 0x62, 0xac,
	0x07, 0x4f, 0xc9, 0x3c, 0xf3, 0xdb, 0x79, 0x9e, 0xd9, 0x85, 0xe3, 0x52, 0x15, 0xa6, 0x18, 0x2b,
	0x92, 0x62, 0x95, 0x91, 0x2a, 0x17, 0xdc, 0x0a, 0xe8, 0x3b, 0x25, 0x18, 0xe5, 0x45, 0x91, 0x2f,
	0x69, 0x6c, 0xf5, 0xc5, 0xfa, 0x65, 0x6c, 0x84, 0x24, 0x6d, 0x52, 0x59, 0x56, 0x68, 0xf4, 0xe1,
	0x81, 0x9f, 0x6c, 0x69, 0xfc, 0x0f, 0x2d, 0x91, 0x31, 0x2f, 0xf4, 0xe2, 0x76, 0xd2, 0x12, 0x19,
	0x32, 0xe8, 0x4b, 0xd2, 0x3a, 0xcd, 0x89, 0xb5, 0x42, 0x2f, 0x1e, 0x24, 0xae, 0xc4, 0x2b, 0xf0,
	0x33, 0x4a, 0xb3, 0xa5, 0x58, 0x11, 0x6b, 0x87, 0x5e, 0x3c, 0x9c, 0x04, 0xbc, 0xb2, 0xe2, 0xce,
	0x8a, 0x3f, 0x38, 0xab, 0xa4, 0x66, 0x11, 0xa1, 0x63, 0xd2, 0x5c, 0xb3, 0x4e, 0xd8, 0x8e, 0x07,
	0x89, 0xfd, 0xc7, 0x11, 0x0c, 0x0d, 0xa5, 0xf2, 0x49, 0x92, 0x5c, 0x90, 0x62, 0x5d, 0xeb, 0x04,
	0x5f, 0xd2, 0xbd, 0x55, 0x30, 0x00, 0xbf, 0x54, 0xa2, 0x50, 0xc2, 0x6c, 0x58, 0xcf, 0x86, 0xab,
	0xeb, 0xe8, 0x1c, 0x0e, 0x5c, 0xfc, 0x84, 0x5e, 0xd7, 0xa4, 0x4d, 0x73, 0x8b, 0x68, 0x0a, 0x87,
	0x3b, 0x44, 0x97, 0xc5, 0x4a, 0x13, 0x72, 0xa8, 0xef, 0xc8, 0x92, 0xc3, 0x09, 0x72, 0x27, 0xf0,
	0x9a, 0xae, 0x99, 0x68, 0x06, 0x38, 0x27, 0xd3, 0x74, 0xfa, 0xeb, 0x94, 0x0b, 0x38, 0xfa, 0x36,
	0x65, 0x1b, 0xa6, 0x11, 0x78, 0xf2, 0xee, 0xed, 0x96, 0x9a, 0x93, 0x7a, 0x13, 0xcf, 0x84, 0xd7,
	0xf0, 0xef, 0xc6, 0x1d, 0x9d, 0x6e, 0xee, 0x66, 0x78, 0xb2, 0xc7, 0xa9, 0x8a, 0x15, 0x04, 0xfb,
	0x5a, 0x5b, 0xaf, 0x5b, 0x18, 0xd4, 0x11, 0xf0, 0x74, 0x07, 0xfe, 0xdc, 0x2e, 0x38, 0xfb, 0xa5,
	0x5b, 0x4d, 0x9a, 0xf6, 0x1f, 0xbb, 0xd5, 0x53, 0xf7, 0xec, 0xe7, 0xf2, 0x33, 0x00, 0x00, 0xff,
	0xff, 0xbb, 0xb9, 0xf0, 0x64, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReminderServiceClient is the client API for ReminderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReminderServiceClient interface {
	GetRemindByID(ctx context.Context, in *ReminderRequest, opts ...grpc.CallOption) (*ReminderResponse, error)
	SetRemind(ctx context.Context, in *SetReminderRequest, opts ...grpc.CallOption) (*SetReminderResponse, error)
}

type reminderServiceClient struct {
	cc *grpc.ClientConn
}

func NewReminderServiceClient(cc *grpc.ClientConn) ReminderServiceClient {
	return &reminderServiceClient{cc}
}

func (c *reminderServiceClient) GetRemindByID(ctx context.Context, in *ReminderRequest, opts ...grpc.CallOption) (*ReminderResponse, error) {
	out := new(ReminderResponse)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/GetRemindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) SetRemind(ctx context.Context, in *SetReminderRequest, opts ...grpc.CallOption) (*SetReminderResponse, error) {
	out := new(SetReminderResponse)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/SetRemind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReminderServiceServer is the server API for ReminderService service.
type ReminderServiceServer interface {
	GetRemindByID(context.Context, *ReminderRequest) (*ReminderResponse, error)
	SetRemind(context.Context, *SetReminderRequest) (*SetReminderResponse, error)
}

// UnimplementedReminderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReminderServiceServer struct {
}

func (*UnimplementedReminderServiceServer) GetRemindByID(ctx context.Context, req *ReminderRequest) (*ReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemindByID not implemented")
}
func (*UnimplementedReminderServiceServer) SetRemind(ctx context.Context, req *SetReminderRequest) (*SetReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRemind not implemented")
}

func RegisterReminderServiceServer(s *grpc.Server, srv ReminderServiceServer) {
	s.RegisterService(&_ReminderService_serviceDesc, srv)
}

func _ReminderService_GetRemindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).GetRemindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/GetRemindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).GetRemindByID(ctx, req.(*ReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_SetRemind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).SetRemind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/SetRemind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).SetRemind(ctx, req.(*SetReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReminderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reminder.ReminderService",
	HandlerType: (*ReminderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemindByID",
			Handler:    _ReminderService_GetRemindByID_Handler,
		},
		{
			MethodName: "SetRemind",
			Handler:    _ReminderService_SetRemind_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reminderpb.proto",
}
