// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dummypb.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestDummy struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDummy) Reset()         { *m = RequestDummy{} }
func (m *RequestDummy) String() string { return proto.CompactTextString(m) }
func (*RequestDummy) ProtoMessage()    {}
func (*RequestDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_54852255984f57e3, []int{0}
}

func (m *RequestDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDummy.Unmarshal(m, b)
}
func (m *RequestDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDummy.Marshal(b, m, deterministic)
}
func (m *RequestDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDummy.Merge(m, src)
}
func (m *RequestDummy) XXX_Size() int {
	return xxx_messageInfo_RequestDummy.Size(m)
}
func (m *RequestDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDummy.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDummy proto.InternalMessageInfo

func (m *RequestDummy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseDummy struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseDummy) Reset()         { *m = ResponseDummy{} }
func (m *ResponseDummy) String() string { return proto.CompactTextString(m) }
func (*ResponseDummy) ProtoMessage()    {}
func (*ResponseDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_54852255984f57e3, []int{1}
}

func (m *ResponseDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDummy.Unmarshal(m, b)
}
func (m *ResponseDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDummy.Marshal(b, m, deterministic)
}
func (m *ResponseDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDummy.Merge(m, src)
}
func (m *ResponseDummy) XXX_Size() int {
	return xxx_messageInfo_ResponseDummy.Size(m)
}
func (m *ResponseDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDummy.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDummy proto.InternalMessageInfo

func (m *ResponseDummy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestDummy)(nil), "dummy.RequestDummy")
	proto.RegisterType((*ResponseDummy)(nil), "dummy.ResponseDummy")
}

func init() { proto.RegisterFile("proto/dummypb.proto", fileDescriptor_54852255984f57e3) }

var fileDescriptor_54852255984f57e3 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x29, 0xcd, 0xcd, 0xad, 0x2c, 0x48, 0xd2, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x5c,
	0x25, 0x25, 0x2e, 0x9e, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x17, 0x10, 0x5f, 0x48, 0x88,
	0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x52,
	0xe6, 0xe2, 0x0d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0xa9, 0xc8, 0xc8, 0x89, 0x8b,
	0x07, 0x2c, 0x19, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc4, 0xc5, 0xea, 0x91, 0x9a,
	0x93, 0x93, 0x2f, 0x24, 0xac, 0x07, 0xb6, 0x49, 0x0f, 0xd9, 0x1a, 0x29, 0x11, 0xb8, 0x20, 0x92,
	0xb9, 0x4e, 0xbc, 0x51, 0xdc, 0x60, 0x61, 0x7d, 0xb0, 0x13, 0x93, 0xd8, 0xc0, 0x94, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0x92, 0x32, 0x42, 0xc0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DummyServiceClient is the client API for DummyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DummyServiceClient interface {
	Hello(ctx context.Context, in *RequestDummy, opts ...grpc.CallOption) (*ResponseDummy, error)
}

type dummyServiceClient struct {
	cc *grpc.ClientConn
}

func NewDummyServiceClient(cc *grpc.ClientConn) DummyServiceClient {
	return &dummyServiceClient{cc}
}

func (c *dummyServiceClient) Hello(ctx context.Context, in *RequestDummy, opts ...grpc.CallOption) (*ResponseDummy, error) {
	out := new(ResponseDummy)
	err := c.cc.Invoke(ctx, "/dummy.DummyService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DummyServiceServer is the server API for DummyService service.
type DummyServiceServer interface {
	Hello(context.Context, *RequestDummy) (*ResponseDummy, error)
}

// UnimplementedDummyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDummyServiceServer struct {
}

func (*UnimplementedDummyServiceServer) Hello(ctx context.Context, req *RequestDummy) (*ResponseDummy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterDummyServiceServer(s *grpc.Server, srv DummyServiceServer) {
	s.RegisterService(&_DummyService_serviceDesc, srv)
}

func _DummyService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDummy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummyServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummy.DummyService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummyServiceServer).Hello(ctx, req.(*RequestDummy))
	}
	return interceptor(ctx, in, info, handler)
}

var _DummyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dummy.DummyService",
	HandlerType: (*DummyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _DummyService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dummypb.proto",
}
